### ISSUE TITLE
Extension does show a blank Page

### ISSUE THREAD

**Issue by maltevesper** [cribeiro84/azure-devops-pull-request-hub#138] opened 2020-07-30 09:16 UTC
### Version Info
Without warning the extension Broke,
note that the extension was Working in this Version (which was installed yesterday), and then broke. I.e. the updated did not immediately break it. Shortly before I used the clear all filters button which I had not used before, but I am not sure if that is related at all.

The Installed Version: Updated version to **1.20200728.1**

_**edit**: This issue is mostly resolved, I leave the logs below for reference, see the first comment for some warnings that still creep up._

### Issue in Chrome
Currently, when switching to the extension page there is a brief flicker (which I assume to be the filter bar of the extension) when trying to load the extension, then a blank page is displayed. Developer console output:

```
Base URL reference: https://<company>/tfs/DefaultCollection/RTLib/_apps/hub/caribeiro84.pull-request-manager-hub.view
PullRequestsTab.tsx:338 Set base URL: https://<company>/tfs/DefaultCollection/
PullRequestsTab.tsx:274 TypeError: Cannot read property 'id' of undefined
    at i.<anonymous> (PullRequestsTab.tsx:288)
    at u (runtime.js:45)
    at Generator._invoke (runtime.js:274)
    at Generator.forEach.e.<computed> [as next] (runtime.js:97)
    at r (asyncToGenerator.js:3)
    at s (asyncToGenerator.js:25)
    at asyncToGenerator.js:32
    at new Promise (<anonymous>)
    at i.<anonymous> (asyncToGenerator.js:21)
    at i.<anonymous> (PullRequestsTab.tsx:81)
react-dom.production.min.js:198 TypeError: Cannot read property 'text' of undefined
    at n.renderSelectedItems (DropdownFilterBarItem.js:87)
    at a (DropdownExpandableButton.js:11)
    at Ho (react-dom.production.min.js:150)
    at Ri (react-dom.production.min.js:178)
    at Fa (react-dom.production.min.js:232)
    at za (react-dom.production.min.js:233)
    at Ss (react-dom.production.min.js:249)
    at Is (react-dom.production.min.js:248)
    at gs (react-dom.production.min.js:245)
    at Ha (react-dom.production.min.js:243)
ra @ react-dom.production.min.js:198
n.callback @ react-dom.production.min.js:210
Yi @ react-dom.production.min.js:193
Qi @ react-dom.production.min.js:193
Na @ react-dom.production.min.js:217
Aa @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ts @ react-dom.production.min.js:250
Ss @ react-dom.production.min.js:249
Is @ react-dom.production.min.js:248
gs @ react-dom.production.min.js:245
Ha @ react-dom.production.min.js:243
enqueueSetState @ react-dom.production.min.js:130
I.setState @ react.production.min.js:13
value @ PullRequestsTab.tsx:275
(anonymous) @ PullRequestsTab.tsx:261
Promise.catch (async)
(anonymous) @ PullRequestsTab.tsx:260
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ PullRequestsTab.tsx:241
Promise.then (async)
(anonymous) @ PullRequestsTab.tsx:242
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
Promise.then (async)
r @ asyncToGenerator.js:13
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
Promise.then (async)
(anonymous) @ PullRequestsTab.tsx:230
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ PullRequestsTab.tsx:81
(anonymous) @ PullRequestsTab.tsx:142
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
Promise.then (async)
(anonymous) @ PullRequestsTab.tsx:139
u @ runtime.js:45
(anonymous) @ runtime.js:274
forEach.e.<computed> @ runtime.js:97
r @ asyncToGenerator.js:3
s @ asyncToGenerator.js:25
(anonymous) @ asyncToGenerator.js:32
(anonymous) @ asyncToGenerator.js:21
(anonymous) @ PullRequestsTab.tsx:81
Na @ react-dom.production.min.js:216
Aa @ react-dom.production.min.js:220
(anonymous) @ react-dom.production.min.js:250
t.unstable_runWithPriority @ scheduler.production.min.js:18
Ts @ react-dom.production.min.js:250
Ss @ react-dom.production.min.js:249
Is @ react-dom.production.min.js:248
gs @ react-dom.production.min.js:245
Ha @ react-dom.production.min.js:243
Os @ react-dom.production.min.js:253
ks @ react-dom.production.min.js:253
As.render @ react-dom.production.min.js:261
(anonymous) @ react-dom.production.min.js:264
Rs @ react-dom.production.min.js:251
Fs @ react-dom.production.min.js:264
render @ react-dom.production.min.js:266
704 @ common.tsx:8
l @ index.html:1
383 @ main.4f80e67b.chunk.js:1
l @ index.html:1
t @ index.html:1
r @ index.html:1
(anonymous) @ main.4f80e67b.chunk.js:1
Show 32 more frames
DropdownFilterBarItem.js:87 Uncaught (in promise) TypeError: Cannot read property 'text' of undefined
    at n.renderSelectedItems (DropdownFilterBarItem.js:87)
    at a (DropdownExpandableButton.js:11)
    at Ho (react-dom.production.min.js:150)
    at Ri (react-dom.production.min.js:178)
    at Fa (react-dom.production.min.js:232)
    at za (react-dom.production.min.js:233)
    at Ss (react-dom.production.min.js:249)
    at Is (react-dom.production.min.js:248)
    at gs (react-dom.production.min.js:245)
    at Ha (react-dom.production.min.js:243)
```

### Issue in Internet Explorer
Site says the extension is taking longer to load, wont load at all.

Developer console:
![image](https://user-images.githubusercontent.com/10866845/88904637-9d387f00-d255-11ea-811b-1083e9d4e31f.png)

Note: the `main.4f80e67b.chunk.js` refers to `FilterBarHub.tsx` line 46 (the line with `.map`)

```
export const alternateStatusPr: Data.IKeyValueData[] = Object.keys(
  Data.AlternateStatusPr
)
  .map((item, index) => {
    return {
      id: Object.values(Data.AlternateStatusPr)[index].toString(),
      text: Object.values(Data.AlternateStatusPr)[index].toString(),
    };
  });
```

**Comment by maltevesper** [comment] 2020-07-30 09:39
Ok, it is working now again, and suddenly the newly added tabs (recently completed/abondened) show up. Sometimes the tabs wont get data if switching between them quickly (switch back and forth between tabs, then wait on a tab to complete loading), and the following shows up in the console:

![image](https://user-images.githubusercontent.com/10866845/88906942-55ffbd80-d258-11ea-9876-1e899a8fd493.png)

I am not sure why I saw the issue/ did not see the tabs before: I guess it is an issue with stale files, despite me force realoding with ctrl+f5. As far as I am concerned this issue can be closed, nevertheless it might be worthfile to fix the invalid access (see the picture in this comment). Internet explorer still does not work, but I don't mind that that is not supported, it was just the only other browser that was installed.

Side note on the work in progress alternate tabs: The counts behind the tab titles drop to 0 until I activate the tabs, and they do that when refreshing the page too. And the sorting on the "when" column dos not seem to be working, it changes the arrow icon, but the order of the pull requests remains the same.

**Comment by mitchello** [comment] 2020-07-31 08:04
We're facing the same issue on our side but with the following trace : 
`TypeError: Cannot read property 'text' of undefined
    at n.renderSelectedItems (DropdownFilterBarItem.js:87)
    at a (DropdownExpandableButton.js:11)
    at Ho (react-dom.production.min.js:150)
    at Ri (react-dom.production.min.js:178)
    at Fa (react-dom.production.min.js:232)
    at za (react-dom.production.min.js:233)
    at Ss (react-dom.production.min.js:249)
    at Is (react-dom.production.min.js:248)
    at gs (react-dom.production.min.js:245)
    at Ha (react-dom.production.min.js:243)`

`Uncaught (in promise) TypeError: Cannot read property 'text' of undefined
    at n.renderSelectedItems (DropdownFilterBarItem.js:87)
    at a (DropdownExpandableButton.js:11)
    at Ho (react-dom.production.min.js:150)
    at Ri (react-dom.production.min.js:178)
    at Fa (react-dom.production.min.js:232)
    at za (react-dom.production.min.js:233)
    at Ss (react-dom.production.min.js:249)
    at Is (react-dom.production.min.js:248)
    at gs (react-dom.production.min.js:245)
    at Ha (react-dom.production.min.js:243)`

I think it's linked to saved filters because only users with filters have this issue.

**Comment by vguzmanp** [comment] 2020-07-31 09:41
I had the same issue. 

Following @mitchello's comment, I cleared the localStorage for the extension, and everything started working fine.

**Comment by cribeiro84** [comment] 2020-07-31 12:24
Thank all of you for the feedback and I'm really sorry for the issues caused by the recent release. The workaround is to clear up the localStorage on the browser you are using so it can be gone. We are working on improvements to avoid that in the future.

**Comment by cribeiro84** [comment] 2020-08-02 22:17
This issue is should be fixed in this new today's release. Please let me know in case of it's still persisting.

Thank you all for the feedback..

**Closed by cribeiro84** 2020-08-02 22:17 UTC
Labels: bug
