### ISSUE TITLE
Pull request links not valid for on-premise Azure DevOps Server 2019

### ISSUE THREAD

**Issue by FatFrag** [cribeiro84/azure-devops-pull-request-hub#163] opened 2020-12-17 09:39 UTC
**Describe the bug**
Pull request links are broken for on-premises Azure DevOps Server 2019

**To Reproduce**
On Pull Request Manager Hub page we click on the URL to pull request and get 404 error because URL does not contain /tfs/collection name

Broken URL is  http://tfsserver:8080//Project/_git/reponame/pullrequest/12345 
Working URL is http://tfsserver:8080/tfs/collectionname/_git/reponame/pullrequest/12345

**Desktop (please complete the following information):**
 - OS: Windows 10 1909
 - Browser Chrome
 - Version 87
- Azure DevOps Server 2019 update 1

**Comment by dneduva** [comment] 2021-01-17 14:43
Same issue with On-Prem 2020 +
Just need to add the collection name into the URI

**Comment by SDohle** [comment] 2021-03-29 10:01
This is still an issue (on prem 2020). Any plans to fix that?

**Comment by cribeiro84** [comment] 2021-03-30 20:02
I do want to fix it but unfortunately I don't have an onprem environment to test it. Would you be able to create a PR for fixing it?

**Comment by SDohle** [comment] 2021-03-31 09:05
The bug appears sporadically in our setup. Currently it working as expected. And I have no idea why it's working sometimes and sometimes not... If it occurs again I will try to fix it and share my fix here.

**Comment by cribeiro84** [comment] 2021-04-01 00:12
I know where the problem is but I don't have a way to test the adjustments. On the Init page method I call an API to get the ADO url, however, the API doesn't work in OnPrem install, then I get it from Referrer and when you load for the first time the extension, it's there but when you requests it to refresh the results, it looses the data.

**Comment by SDohle** [comment] 2021-04-01 06:16
I suspected the same code fragment. What do you mean by "when you requests it to refresh the results"? I've no idea how to reproduce the bug currently, everything is working fine...

**Comment by cribeiro84** [comment] 2021-04-01 10:02
You can try to simulate by clicking on the refresh button of the filters:

![image](https://user-images.githubusercontent.com/328635/113278238-117d6380-92b8-11eb-9862-2da52ce79eeb.jpeg)

It's there that usually it looses the data.

**Comment by SDohle** [comment] 2021-04-01 10:37
The refresh button duplicates all entries in the filter dropdown. But does not break the PR links (currently).

**Comment by cribeiro84** [comment] 2021-04-01 10:44
So it's worst that I thought 😄
I and I could simulate the duplicated items from my end. I'll look into it also. However, for the broken links I don't have an environment to try that out 😕

**Comment by cribeiro84** [comment] 2021-04-03 00:07
A new version is released with this fix. Could you please test it? Feel free to reopen the issue in case it's still not working.

**Closed by cribeiro84** 2021-04-03 00:07 UTC
Labels: bug, good first issue
