### ISSUE TITLE
Continual Loading Bar 

### ISSUE THREAD

**Issue by rofehaim** [cribeiro84/azure-devops-pull-request-hub#21] opened 2019-09-12 14:25 UTC
Hi,
The extensions look great but seem it's not working for me.
I have Azure DevOps 2019, and I installed the extension but it shows an endless loading bar...
![image](https://user-images.githubusercontent.com/10534113/64792560-47e27900-d582-11e9-83a0-6119511dbc38.png)

**Comment by rofehaim** [comment] 2019-09-15 08:32
Unfortunately this is not the case... I have an open pull requests.
there is one error in the network tab.. attaching screenshots.
![image](https://user-images.githubusercontent.com/10534113/64918813-177e2300-d7ac-11e9-9d90-7b58225f4a4e.png)
![image](https://user-images.githubusercontent.com/10534113/64918847-83f92200-d7ac-11e9-988d-27498ab8fb8d.png)

**Comment by cribeiro84** [comment] 2019-09-15 12:10
Thanks for sending more details @rofehaim, the issue is that the extension is trying to use the 5.2 SDK version and your server supports at this moment only the 5.1. I will investigate whether if I downgrade it to 5.1 it will not affect anything. On the other hand, is there a way for you to update your server to its latest version?

Thank you very much.

**Comment by rofehaim** [comment] 2019-09-15 12:46
I don't think I'm going to upgrade the server anytime soon...

**Comment by cribeiro84** [comment] 2019-11-23 15:53
@rofehaim,
I'm working on a new PR #47 that's downgrading the API version to 5.1. Perhaps, if you could test after it's released will be great.

**Comment by cribeiro84** [comment] 2019-11-23 15:53
Duplicate of #45

**Closed by cribeiro84** 2019-11-23 15:53 UTC
Labels: bug
