### ISSUE TITLE
Last Commit Date Changes to Creation Date on Click

### ISSUE THREAD

**Issue by galarun** [cribeiro84/azure-devops-pull-request-hub#66] opened 2020-01-06 21:39 UTC
When you click anywhere on a row, the last commit date of the PR is changed to the creation date.

See example (Chrome ver. 79.0.3945.88): https://imgur.com/6hmi9aK.gif

**Comment by cribeiro84** [comment] 2020-01-07 00:41
@galarun, thanks for your feedback. It's a known "issue". What happens is that there is an async call to get more details about the PR and its commits and the UI is not being updated accordingly. It will be fixed in the future releases.

**Comment by cribeiro84** [comment] 2020-01-10 14:37
@galarun - I just simulated the issue and it's an expected behavior because I'm using a component from Azure DevOps SDK called <Ago /> and <Duration />... When the component receives any interaction, it updates to last date information due the fact it considers the commit date with the current date (Now).

Therefore, I will close this issue. Feel free to open it again in case something else is happening.

**Closed by cribeiro84** 2020-01-10 14:37 UTC
Labels: bug

**Comment by galarun** [comment] 2020-01-10 16:07
@cribeiro84 I'm not sure I understand.  The "Last Commit Date" field is being changed to the "Pull Request Creation Date" value which is not correct.  Futhermore, my experience in the past couple days has been that the Last Commit Date value is now always the same as the PR Creation Date even on first load.  All the PR requests in my list have Last Commit Date reflecting the Creation Date instead of the actual date when the PR was updated with a commit.

**Comment by cribeiro84** [comment] 2020-01-12 00:13
@galarun I just released a new version of the extension with some fixes for the async calls that capture additional PR info. It was supposed to fix this issue you reported but there is a behaviour for the Ago and Duration components from Azure DevOps that works like a counter based on a start date and DateTime now (current date). Therefore, whenever a new minute goes, the component will update if you interact with the row itself adding one minute or minutes compared to the last rendered time.

 I hope this clarifies and also it has fixed the issue with the Last Commit Date that was working partially and now should be fixed.

**Comment by galarun** [comment] 2020-01-13 13:01
Confirmed it's working now, thank you @cribeiro84!

**Comment by cribeiro84** [comment] 2020-01-13 20:36
Fantastic! Thanks for your feedback :-)
Do not forget to give your rating for the extension in the Azure DevOps marketplace :-)
